#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <sstream>

using namespace std;

// ---------------------------------------------------------
// Data Structures for the Graph Neural Network
// ---------------------------------------------------------

struct QKDLinkMetrics 
{
    string link_id;
    double quantum_bit_error_rate;
    double signal_pulse_count;
    double decoy_pulse_count;
    
    // Labels for the ML model
    bool is_actively_attacked;
    double theoretical_key_rate_loss;
};

struct NetworkTopologyNode 
{
    string node_id;
    bool is_trusted_repeater;
    
    // Edges connected to this node
    vector<QKDLinkMetrics> adjacent_links;
};

// ---------------------------------------------------------
// Parsing Engine
// ---------------------------------------------------------

// Helper function to split a CSV line by comma
vector<string> parse_csv_line(const string& line) 
{
    vector<string> tokens;
    stringstream line_stream(line);
    string cell;
    
    while (getline(line_stream, cell, ',')) 
    {
        tokens.push_back(cell);
    }
    
    return tokens;
}

// Main parser that builds the graph from the SeQUeNCe logs
vector<NetworkTopologyNode> build_graph_from_telemetry(const string& filepath) 
{
    vector<NetworkTopologyNode> network_graph;
    ifstream file(filepath);
    
    if (!file.is_open()) 
    {
        cout << "Error: Could not open simulation log file. Check if the file name is exact." << endl;
        return network_graph;
    }
    
    string line;
    int parsed_rows = 0;
    int skipped_rows = 0;
    
    // Skip the CSV header row
    getline(file, line); 
    
    // Process each recorded link event
    while (getline(file, line)) 
    {
        // Skip entirely blank lines generated by Windows \r\n issues
        if (line.empty() || line == "\r") continue; 
        
        vector<string> data = parse_csv_line(line);
        
        // We are back to checking for 7 columns!
        if (data.size() < 7) 
        {
            if (skipped_rows == 0) 
            {
                cout << "\n[DIAGNOSTIC] Skipped a row! Expected 7 columns, but found " << data.size() << "." << endl;
                cout << "[DIAGNOSTIC] Here is what the C++ parser saw on that line: " << line << "\n" << endl;
            }
            skipped_rows++;
            continue; 
        }
        
        parsed_rows++;
        
        QKDLinkMetrics current_link;
        current_link.link_id                    = data[0];
        current_link.quantum_bit_error_rate     = stod(data[1]);
        current_link.signal_pulse_count         = stod(data[2]);
        current_link.decoy_pulse_count          = stod(data[3]);
        current_link.is_actively_attacked       = (stoi(data[4]) == 1);
        current_link.theoretical_key_rate_loss  = stod(data[5]);
        
        string source_node_id = data[6];
        
        // Windows CRLF fix: Remove trailing '\r' from the last column (which is now source_node_id)
        if (!source_node_id.empty() && source_node_id.back() == '\r') 
        {
            source_node_id.pop_back();
        }
        
        // -------------------------------------------------------------
        // THE SMART FIX: Extract Destination from the Link ID string
        // If Link ID is "Link_Node_A_Node_B" and Source is "Node_A", 
        // we slice out "Node_B" automatically.
        // -------------------------------------------------------------
        string prefix = "Link_" + source_node_id + "_";
        string dest_node_id = current_link.link_id.substr(prefix.length());
        
        
        bool source_found = false;
        bool dest_found   = false;
        
        // Map the link to its corresponding node in the graph
        for (int i = 0; i < network_graph.size(); ++i) 
        {
            if (network_graph[i].node_id == source_node_id) 
            {
                network_graph[i].adjacent_links.push_back(current_link);
                source_found = true;
            }
            if (network_graph[i].node_id == dest_node_id) 
            {
                network_graph[i].adjacent_links.push_back(current_link);
                dest_found = true;
            }
        }
        
        // If the source node doesn't exist yet, create it
        if (!source_found) 
        {
            NetworkTopologyNode new_node;
            new_node.node_id = source_node_id;
            
            // In a diamond topology, endpoints aren't repeaters
            new_node.is_trusted_repeater = (source_node_id == "Node_B" || source_node_id == "Node_C");
            
            new_node.adjacent_links.push_back(current_link);
            network_graph.push_back(new_node);
        }
        
        // If the destination node doesn't exist yet, create it
        if (!dest_found) 
        {
            NetworkTopologyNode new_node;
            new_node.node_id = dest_node_id;
            
            new_node.is_trusted_repeater = (dest_node_id == "Node_B" || dest_node_id == "Node_C");
            
            new_node.adjacent_links.push_back(current_link);
            network_graph.push_back(new_node);
        }
    }
    
    cout << "[DIAGNOSTIC] Total valid rows parsed successfully: " << parsed_rows << endl;
    if (skipped_rows > 0) cout << "[DIAGNOSTIC] Total rows skipped: " << skipped_rows << endl;
    
    file.close();
    return network_graph;
}

// ---------------------------------------------------------
// Execution
// ---------------------------------------------------------

int main() 
{
    // Point this to the output file generated by your Python SeQUeNCe script
    string log_file = "sequence_telemetry_output.csv";
    
    cout << "Initializing SeQUeNCe Log Parser..." << endl;
    
    vector<NetworkTopologyNode> parsed_graph = build_graph_from_telemetry(log_file);
    
    cout << "Graph successfully constructed in memory." << endl;
    cout << "Total Nodes Parsed: " << parsed_graph.size() << endl;
    
    return 0;
}