#include <iostream>
#include <vector>
#include <string>
#include <fstream>
#include <sstream>

using namespace std;

// Helper to split a CSV line by comma
vector<string> parse_csv_line(const string& line) 
{
    vector<string> tokens;
    stringstream line_stream(line);
    string cell;
    
    while (getline(line_stream, cell, ',')) 
    {
        tokens.push_back(cell);
    }
    
    return tokens;
}

// Map the string node names to PyTorch integer IDs
int get_node_id(const string& node_name)
{
    if (node_name == "Node_A") return 0;
    if (node_name == "Node_B") return 1;
    if (node_name == "Node_C") return 2;
    if (node_name == "Node_D") return 3;
    
    return -1;
}

int main() 
{
    string input_file         = "sequence_telemetry_output.csv";
    string edge_index_file    = "pytorch_edge_index.csv";
    string edge_features_file = "pytorch_edge_features.csv";
    
    ifstream in_file(input_file);
    ofstream out_index(edge_index_file);
    ofstream out_features(edge_features_file);
    
    if (!in_file.is_open()) 
    {
        cout << "Error: Could not open " << input_file << ". Did you run starter.py?" << endl;
        return 1;
    }
    
    // Write headers for Avyukth's PyTorch Data Loader
    out_index << "source_idx,dest_idx" << endl;
    out_features << "graph_id,qber,signal_count,decoy_count,is_attacked,key_loss" << endl;
    
    string line;
    
    // Skip the original CSV header row
    getline(in_file, line); 
    
    int row_count = 0;
    
    while (getline(in_file, line)) 
    {
        // Skip entirely blank lines generated by Windows \r\n issues
        if (line.empty() || line == "\r") continue;
        
        vector<string> data = parse_csv_line(line);
        
        // Ensure the row has the 7 columns
        if (data.size() < 7) continue;
        
        // Extract the numerical features
        string link_id     = data[0];
        string qber        = data[1];
        string signal      = data[2];
        string decoy       = data[3];
        string is_attacked = data[4];
        string key_loss    = data[5];
        
        string source_node_id = data[6];
        
        // Windows CRLF fix
        if (!source_node_id.empty() && source_node_id.back() == '\r') 
        {
            source_node_id.pop_back();
        }
        
        // Extract Destination from the Link ID string
        string prefix = "Link_" + source_node_id + "_";
        string dest_node_id = link_id.substr(prefix.length());
        
        // Convert Node_A, Node_B to 0, 1, etc.
        int src_idx = get_node_id(source_node_id);
        int dst_idx = get_node_id(dest_node_id);
        
        // Group every 4 links into 1 network graph snapshot (Epoch)
        int graph_id = row_count / 4; 
        
        // Output to PyTorch formatted files
        out_index << src_idx << "," << dst_idx << endl;
        
        out_features << graph_id << "," 
                     << qber << "," 
                     << signal << "," 
                     << decoy << "," 
                     << is_attacked << "," 
                     << key_loss << endl;
        
        row_count++;
    }
    
    in_file.close();
    out_index.close();
    out_features.close();
    
    cout << "------------------------------------------------" << endl;
    cout << "Serialization Complete!" << endl;
    cout << "Processed " << row_count / 4 << " multi-hop graphs." << endl;
    cout << "Generated: " << edge_index_file << endl;
    cout << "Generated: " << edge_features_file << endl;
    cout << "Push these to GitHub for Avyukth!" << endl;
    cout << "------------------------------------------------" << endl;
    
    return 0;
}